name: CI - Build and Test

on:
  pull_request:
    branches: [master]
  push:
    branches:
      - master
      - '**'  # Run on all branches

jobs:
  build:
    name: Build
    runs-on: windows-latest
    strategy:
      matrix:
        mode: [release, dev]

    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.23.3"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build deej (${{ matrix.mode }})
        run: pkg/deej/scripts/windows/build-${{ matrix.mode }}.bat
        shell: cmd

      - name: Archive build artifact
        if: matrix.mode == 'release' && github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v4
        with:
          name: windows-build-master
          path: deej-release.exe
          retention-days: 30

